/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "qsk_led.h"

// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 
void main(void)
{
	int count = 0;
	
	mcu_init();
	
	// Initialize LEDs
	InitLED();

	while(1) {

		switch( count ) {
			case 0:
			OffLED(G_LED);
			OnLED(R_LED);
			break;
			
			case 1:
			OffLED(R_LED);
			OnLED(Y_LED);
			break;
			
			case 2:
			OffLED(Y_LED);
			OnLED(G_LED);
			break;
			
			default:
			count = -1; 
			break;
		}
		count++;
		Delay(15000);
	}	
}
